server:
  port: 8003
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifecapsule3
    username: postgres
    password: 112233ccddEE
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: logs/metazone.log